### ISSUE TITLE
Don't ping a still connectiong socket

### ISSUE THREAD

**Issue by markg85** [nknorg/nkn-shell-daemon#2]
Hi,

The current code calls ping() on a websocket.
In my case, i do sometimes see a stack trace at that very call because the socket does exist but isn't connected yet.

The fix would be to only pong when the socket is connected.
For instance with code like this in the client connect callback (client here is an nknClient instance): `client.ws.readyState === WebSocket.OPEN` But this requires access to the WebSocket object which you don't have by default. You could add a `const WebSocket = require('isomorphic-ws');` which does add it as dependency (might be ok). A more graceful way is to probably go with a ping function within nknClient so that it handles ping requests internally in it's library.

Cheers,
Mark

**Comment by yilunzhang** [comment]
Sorry for the late reply. I forgot to subscribe to this repo, so I completely missed your issues until today..

I have fixed this issue by checking readyState as you suggested.

> A more graceful way is to probably go with a ping function within nknClient so that it handles ping requests internally in it's library.

The ping here actually (almost) doesn't do anything because in js WebSocket does not expose an interface to get notified when received ws pong message. In addition, IIRC the websocket behavior is a bit different in Browser and no ping method is exposed at all... The reason we have ping logic here is to trigger TCP keepalive and prevent it from idle. It's not needed now since the same logic is added at node side recently.
